import = [
  "~/.config/alacritty/themes/github_dark_dimmed.yml"
]

[env]
term = "xterm-256color"

[scrolling]
history = 10000

[font]
size = 15.0
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
