# Set tmux colours
set -g default-terminal "screen-256color"

# Start status line (airline)
if-shell "test -f ~/.tmux-status.conf" "source ~/.tmux-status.conf"

# Enable mouse scrolling
set -g mouse on
