# Set tmux colours
set -g default-terminal "screen-256color"

# Start status line (airline)
if-shell "test -f ~/.tmux-status.conf" "source ~/.tmux-status.conf"

# Enable mouse scrolling
set -g mouse on

# Use system clipboard
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"

# Use vim keys
set-window-option -g mode-keys vi
